---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/clients":
    post:
      summary: Create client
      tags:
      - Clients
      parameters: []
      responses:
        '201':
          description: Client created
        '422':
          description: Invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                phone_number:
                  type: string
                operator_code:
                  type: string
                tag:
                  type: string
                timezone:
                  type: string
              required:
              - phone_number
              - operator_code
              - tag
              - timezone
  "/clients/{id}":
    put:
      summary: Update client
      tags:
      - Clients
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Client updated
        '404':
          description: Client not found
        '422':
          description: Invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                phone_number:
                  type: string
                operator_code:
                  type: string
                tag:
                  type: string
                timezone:
                  type: string
              required:
              - phone_number
              - operator_code
              - tag
              - timezone
    delete:
      summary: delete client
      tags:
      - Clients
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Client deleted
        '404':
          description: Client not found
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
