---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/clients":
    post:
      summary: Create client
      tags:
      - Clients
      parameters: []
      responses:
        '201':
          description: Client created
        '422':
          description: Invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                phone_number:
                  type: string
                operator_code:
                  type: string
                tag:
                  type: string
                timezone:
                  type: string
              required:
              - phone_number
              - operator_code
              - tag
              - timezone
  "/clients/{id}":
    put:
      summary: Update client
      tags:
      - Clients
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Client updated
        '404':
          description: Client not found
        '422':
          description: Invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                phone_number:
                  type: string
                operator_code:
                  type: string
                tag:
                  type: string
                timezone:
                  type: string
              required:
              - phone_number
              - operator_code
              - tag
              - timezone
    delete:
      summary: Delete client
      tags:
      - Clients
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Client deleted
        '404':
          description: Client not found
  "/notifications":
    post:
      summary: Create notification
      tags:
      - Notifications
      parameters: []
      responses:
        '201':
          description: Notification created
        '422':
          description: Invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                start_at:
                  type: string
                text:
                  type: string
                filter:
                  type: string
                end_at:
                  type: string
              required:
              - start_at
              - text
              - filter
              - end_at
  "/notifications/{id}":
    put:
      summary: Update notification
      tags:
      - Notifications
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Notification updated
        '422':
          description: Invalid request
        '404':
          description: Notification not found
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                start_at:
                  type: string
                text:
                  type: string
                filter:
                  type: string
                end_at:
                  type: string
              required:
              - start_at
              - text
              - filter
              - end_at
    delete:
      summary: Delete notification
      tags:
      - Notifications
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Notification deleted
        '404':
          description: Notification not found
  "/notifications/statistics":
    get:
      summary: Get statistics
      tags:
      - Notifications
      responses:
        '200':
          description: OK
  "/notifications/{id}/statistics":
    get:
      summary: Get notification details
      tags:
      - Notifications
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
